### ISSUE TITLE
for F in $(ls *.yaml); do kubectl create -f $F; done shows error

### ISSUE THREAD

**Issue by Arsh-ak7** [rahullrajesh/implement-devops#15]
error: unable to recognize deployment-prod-backend.yaml: no matches for kind Deployment in version extensions/v1beta1

when i run it shows the above error

**Comment by tanmay380** [comment]
for me its showing "The connection to the server localhost:8080 was refused - did you specify the right host or port?"

**Comment by Arsh-ak7** [comment]
@tanmay380 
You're talking about task three?

**Comment by tanmay380** [comment]
> @tanmay380
> You're talking about task three?
https://github.com/rahullrajesh/implement-devops/blob/master/Deploy%20and%20Manage%20Cloud%20Environments%20with%20Google%20Cloud:%20Challenge%20Lab isme line number 21.

**Comment by tanmay380** [comment]
> @tanmay380
> You're talking about task three?

Nahi task 1 mein hi.. vo maine ek line nahi likhi islie nahi chal paa rha tha.. nvm

**Comment by Arsh-ak7** [comment]
@tanmay380 
Okay!
If you'd complete task three as well do tell 😄

**Comment by tanmay380** [comment]
@Arsh-ak7  I'm unable to do task 1.... ur talking about task 3 lol

**Comment by Arsh-ak7** [comment]
@tanmay380 
You're using the jumphost ssh?

**Comment by tanmay380** [comment]
yup... maine videos mein dekha tha to usse hi follow kar rha tha..

**Comment by C19H3R** [comment]
i am also facing the same issue

**Comment by tanmay380** [comment]
@Arsh-ak7 bhai how u have solved it. Can you please share something?

**Comment by Arsh-ak7** [comment]
@tanmay380 I haven't.

**Comment by iamirulofficial** [comment]
I think api versions are old, 
extensions/v1beta1 must be having problem i guess!

**Comment by Arsh-ak7** [comment]
@iamirulofficial the extension problem is solved for me.
I don't see the spin-deck pod which is supposedly created from before.

**Comment by THANUJAK123** [comment]
i dint get task 2 ,3 and 5 
howv

**Comment by iamirulofficial** [comment]
Actually this lab 
`Deploy and Manage Cloud Environments with Google Cloud: Challenge Lab` is having some problem, concerned team is looking into it, till then perform other labs,

**Comment by THANUJAK123** [comment]
tq for ur response

**Comment by THANUJAK123** [comment]
Migrate a MySQL Database to Google Cloud SQL
in this lab also after giving password it shows acces denied
can u help me out

**Comment by deepak852k1** [comment]
In task 1 i got an error as "please create frontent and backend development enviroinment". please anyone help me i have less number of credits
